config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  
  # Static pages
  get 'club', to: 'static_pages#club'
  # Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
  resources :users
  get 'signup', to: 'users#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :password, presence: true
  has_secure_password
  
  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Successfully logged in!"
      redirect_to root_path
    else
      flash[:danger] = "Invalid username/password"
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    flash[:info] = "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def club
    unless logged_in?
      flash[:warning] = "You must be logged in to access to this page"
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  def show
    if logged_in?
     @user = User.find(params[:id])
     else
      flash[:error] = "You must be logged in to access this page"
      redirect_to login_path
    end

    if session[:user_id].to_i != params[:id].to_i
      flash[:error] = "You're not allowed to access this page"
      redirect_to root_path
    end
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "You've successfully signed up, welcome !"
      redirect_to root_path
    else
      flash[:danger] = "Sign-up failed, please try again."
      redirect_to signup_path
    end
  end
  def edit
   @user = User.find(session[:id])
  end
   def update
    @user = User.find(session[:id])
    @user.first_name = 
    redirect_to user_path
   end


  def destroy
    @user.destroy
    flash[:info] = "Account successfully deleted, sorry to see you go."
  end
  
  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end
  
  def log_out
    session.delete(:user_id)
    redirect_to root_path
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">42</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to 'Home', root_path, class: "nav-item nav-link"  %>
      <%= link_to 'Club', club_path, class: "nav-item nav-link"  %>
    </div>
  </div>
  <ul class="nav navbar-nav navbar-right">
    <% unless logged_in? %>
    <li>
      <%= link_to 'Sign up', signup_path, class: "nav-item nav-link"  %>
    <li>
      <%= link_to 'Login', login_path, class: "nav-item nav-link" %>
      <% else %>
      <%= link_to 'Logout', logout_path, class: "nav-item nav-link"  %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>TheHackingClub</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>

<body>
  <%= render 'layouts/navbar' %>
  <% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

</body>

</html>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
<div class="form-row">
  <div class="form-group col-md-6">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :confirm_password %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
</div>
<%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% if request.env['PATH_INFO'] =~ /users\/\d\/edit/ && params[:id].to_i == @user.id %>
<%= form_with(model: @user, local: true) do |f| %>
<div class="container" style="width: 600px;">
<div class="form-row">
  <div class="form-group col-md-6">
    <%= f.label :first_name%>:
    <%= f.text_field :first_name, class: "form-control", placeholder: "#{@user.first_name}", :required => true %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control", placeholder: "#{@user.last_name}", :required => true %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control", placeholder: "#{@user.email}", :required => true %>
  </div>
</div>
<%= f.submit "Submit", class: "btn btn-primary" %>
<% if request.env['PATH_INFO'] =~ /users\/\d\/edit/ %>
<%= link_to 'Back', users_path, class: "btn btn-primary" %>
<% end %>
<% end %>
<% else %>
<p>You can't edit this gossip</p>
<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<%= @user.first_name %>
<%= @user.last_name %></br>
<%= @user.email %>
<%= link_to 'Edit profile', edit_user_path(@user), class: "btn btn-primary"%>